const FAILURE_THRESHOLD = 5;
const RECOVERY_THRESHOLD = 20;
const LOOKBACK_PERIOD = 24 * 60 * 60 * 1000; // 24 hours in milliseconds

export { FAILURE_THRESHOLD, RECOVERY_THRESHOLD, LOOKBACK_PERIOD };
