-- AlterTable
ALTER TABLE "Api" ADD COLUMN     "averageResponseTime" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "p90ResponseTime" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "p99ResponseTime" DOUBLE PRECISION NOT NULL DEFAULT 0;
